version: '3'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=metodista_ensino
      - POSTGRES_USER=metodista_ensino
    ports:
      - '5432:5432'
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DBPASSWORD=admin@123
      - DBNAME=metodista_ensino
      - DBUSER=metodista_ensino
      - DBHOSTNAME=postgres
      - DBPORT=5432
    restart: always
    ports:
      - '3001:3000'
  client:
    depends_on:
      - api
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - EXTERNAL_API_URL=http://localhost:3001
      - INTERNAL_API_URL=http://api:3000
    restart: always
    ports:
      - '3000:3000'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
      - client
    ports:
      - '80:80'
