apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: jckonewalik/methodist_education_server
          env:
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: DBNAME
              value: "metodista_ensino"
            - name: DBUSER
              value: "metodista_ensino"
            - name: DBHOSTNAME
              value: "postgres-srv"
            - name: DBPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
